Add DANE and DANE-Related RRs
nix-community/dns.nix pull request #27
Opened 2022-02-09 06:59 UTC by DarkKirb

Some of the zones I manage use TLSA, OPENPGPKEY, SSHFP, and HTTPS resource records.

TLSA allows for pinning a certificate or the public key for the service it is for.
OPENPGPKEY allows looking up public keys on DNS, as opposed to a keyserver
SSHFP allows pinning the expected SSH Public Key hashes to DNS, which helps secure the TOFU model SSH has

The other two added resource records, SVCB and HTTPS, are currently in draft phase, but the latter is already implemented in Chrome and Firefox. The HTTPS record in particular is used as a DNS-based Strict Transport Security policy

The examples for TLSA and OPENPGPKEY I added are not how you are meant to deploy them. I added them to test if my code works.

(This is unchanged from the previous PR which was closed because i renamed the master branch to something more appropriate)

2024-04-17 20:15 UTC, rouven0 commented
Hey there, chiming in a bit late here. Is there anything blocking this from being merged? 👀

2024-04-18 12:10 UTC, RaitoBezarius commented
I will put it on my pile to review it to get again in the dns.nix game :).

2024-11-29 10:23 UTC, felbinger commented
> I will put it on my pile to review it to get again in the dns.nix game :).

Reminder. Any update?

2025-01-14 19:01 UTC, SuperSandro2000 commented
pong @RaitoBezarius @kirelagin @Tom-Hubrecht

2025-01-15 12:00 UTC, Tom-Hubrecht requested changes

2025-01-16 08:45 UTC, ghost commented
thank you!

2025-01-16 10:04 UTC, Tom-Hubrecht commented
> thank you!

Ooops, my suggestions introduced syntax errors... I'll do another review to fix it

2025-01-16 10:09 UTC, Tom-Hubrecht requested changes

2025-01-16 10:09 UTC, Tom-Hubrecht commented on dns/types/records/SSHFP.nix
> +    "${toString algorithm} ${toString mode} ${fingerprint}";
```suggestion
  dataToString = { algorithm, fingerprintType, fingerprint, ... }:
    "${toString algorithm} ${toString fingerprintType} ${fingerprint}";
```

2025-01-16 10:09 UTC, Tom-Hubrecht commented on dns/types/records/SVCB.nix
> +      ) config
```suggestion
  mkSvcParams = params: concatStringsSep " " (
    filter (s: s != "") (
      mapAttrsToList (
        name: value:
        if value == true then
          name
        else if isList value then
          "${name}=${concatStringsSep "," value}"
        else if isInt value then
          "${name}=${builtins.toString value}"
        else
          ""
      ) params
```

2025-01-16 10:09 UTC, Tom-Hubrecht commented on dns/types/records/SVCB.nix
> +rec {
```suggestion
{
```

2025-01-16 10:09 UTC, Tom-Hubrecht commented on dns/types/records/SVCB.nix
> +}"
```suggestion
}";
```

2025-01-16 10:09 UTC, Tom-Hubrecht commented on example.nix
> +        mode = "sha256";
```suggestion
        fingerprintType = "sha256";
```

2025-01-16 10:09 UTC, Tom-Hubrecht commented on example.nix
> +        match = "sha256";
```suggestion
        matchingType = "sha256";
```

2025-01-16 12:56 UTC, SuperSandro2000 commented
FYI #37

Not sure which one to take

2025-01-23 17:24 UTC, merged

2025-01-23 18:24 UTC, felbinger commented
Finally, thanks!