Add HTTPS record type support
nix-community/dns.nix pull request #30
Opened 2024-04-21 14:03 UTC by SuperSandro2000

Cherry-picked from https://github.com/nix-community/dns.nix

2024-05-16 16:01 UTC, Tom-Hubrecht requested changes

2024-05-16 16:01 UTC, Tom-Hubrecht commented on dns/types/records/HTTPS.nix
> +    "${toString priority} ${toString target} " + mkSvcParams { inherit alpn port ipv4hint ipv6hint; };
```suggestion
    "${toString priority} ${target} ${mkSvcParams { inherit alpn port ipv4hint ipv6hint; }}";
```

`target` is already a string

2024-08-06 17:38 UTC, NickCao commented
This is now finally useful as firefox 129 supports HTTPS records with system resolvers: https://www.mozilla.org/en-US/firefox/129.0/releasenotes/

2024-11-02 00:47 UTC, SuperSandro2000 commented on dns/types/records/HTTPS.nix
> +  mkSvcParams = params: lib.concatStringsSep " " (lib.mapAttrsToList (key: value: mkSvcParam key value) params);
Why should we filter empty string when the defaults are null which is already filtered in mkSvcParam?

2025-01-23 17:32 UTC, Tom-Hubrecht commented
Should be included with the merge of #27

2025-01-23 17:32 UTC, closed without merging